develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35732:35729"
  container_name: vocabulary-tag-develop
  environment:
    NODE_ENV: dev
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4100
    DEBUG: "*"
    API_VERSION: v1
    CT_REGISTER_MODE: auto
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/vocabulary-tag/app
mongo:
  image: mongo
  container_name: vocabulary-tag-mongo-develop
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - $HOME/docker/data/vocabulary-tag:/data/db
  restart: always
