test:
  extends:
    file: base.yml
    service: base
  ports:
    - "4100"
  container_name: rw-vocabulary-tag-test
  environment:
    NODE_ENV: test
  command: test
  links:
    - mongo
mongo:
  image: mongo
  container_name: rw-vocabulary-tag-mongo-test
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - $HOME/docker/data/rw-vocabulary-tag:/data/db
  restart: always
